### PR TITLE
minor fixes

### PR DESCRIPTION
**Pull request by mgraupe**

### CODE REVIEW

**Comment by mgraupe** [comment]
I added the possibility to use the task duration as totalDuration in the Scanner Task. It works when the Task Duration is increased but gives an error when the Task Duration is decreased (see below).

Any idea why this is the case? 

```
ValueError: strides is incompatible with shape of requested array and size of buffer
  File "acq4\devices\DAQGeneric\DaqChannelGui.py", line 183, in daqChanged
    self.updateWaves()
  File "acq4\devices\DAQGeneric\DaqChannelGui.py", line 223, in updateWaves
    runSequence(lambda p: waves.append(self.getSingleWave(p)), params, params.keys()) ## appends waveforms for the entire parameter space to waves
  File "acq4\util\SequenceRunner.py", line 14, in runSequence
    return seq.start(func)
  File "acq4\util\SequenceRunner.py", line 78, in start
    self.nloop(func=func)
  File "acq4\util\SequenceRunner.py", line 100, in nloop
    ret = func(params)
  File "acq4\devices\DAQGeneric\DaqChannelGui.py", line 223, in <lambda>
    runSequence(lambda p: waves.append(self.getSingleWave(p)), params, params.keys()) ## appends waveforms for the entire parameter space to waves
  File "acq4\devices\DAQGeneric\DaqChannelGui.py", line 265, in getSingleWave
    wave = self.ui.waveGeneratorWidget.getSingle(self.rate, self.numPts, params)
  File "acq4\util\generator\StimGenerator.py", line 437, in getSingle
    ret = eval(fn.replace('\n', ''), ns, {})
  File "<string>", line 1, in <module>
  File "acq4\util\generator\StimGenerator.py", line 579, in getArray
    return data()
  File "acq4\devices\Scanner\scan_program\program.py", line 245, in generateLaserMask
    mask |= component.scanMask()
  File "acq4\devices\Scanner\scan_program\rect.py", line 57, in scanMask
    rs.writeScanMask(mask)
  File "acq4\devices\Scanner\scan_program\rect.py", line 421, in writeScanMask
    target = pg.subArray(array, offset, shape, stride)
  File "acq4\pyqtgraph\functions.py", line 629, in subArray
    return np.ndarray(buffer=data, shape=shape+extraShape, strides=strides, dtype=data.dtype)
```

**Comment by campagnola** [comment]
I'm just guessing, but is the task duration shorter than a single scan
frame?

**Comment by mgraupe** [comment]
No it's not that.

Increases work without a hitch (e.g. 1-> 2 sec) but decreases (e.g. 2-1
sec) yield the error, even if they seem to be implemented correctly
afterwards and even if the new duration is longer than a single scan frame.

**Comment by campagnola** [comment]
I updated my branch with a somewhat different approach. It works, but there's a weird bug in the interaction between some of the checkboxes that I haven't figured out yet. Main differences:
- didn't need to add ScanProgram.setTotalDuration, since this is redundant with ScanProgram.setSampling
- added the protocol duration option as a sub-parameter of totalDuration in the user interface, rather than inserting it into the system

**Comment by mgraupe** [comment]
Your approach works here. I am happy to adapt it.

The only problem with the current implementation is that the
"useTaskDuration" child of "totalDuration" is not saved with the scan
program parameters. Could that be added?

Thanks,
Michael

On Fri, Apr 15, 2016 at 9:16 PM, Luke Campagnola notifications@github.com
wrote:

> I updated my branch with a somewhat different approach. It works, but
> there's a weird bug in the interaction between some of the checkboxes that
> I haven't figured out yet. Main differences:
> - didn't need to add ScanProgram.setTotalDuration, since this is
>   redundant with ScanProgram.setSampling
> - added the protocol duration option as a sub-parameter of
>   totalDuration in the user interface, rather than inserting it into the
>   system
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/campagnola/acq4/pull/1#issuecomment-210604106

## 

Michael Graupner (PhD)
Brain Physiology Lab, Université Paris Descartes
http://www.biomedicale.parisdescartes.fr/~mgraupe/
michael.graupner@parisdescartes.fr

**Comment by mgraupe** [comment]
Any hints on how to save "useTaskDuration"?

Thanks,
Michael

**Comment by campagnola** [comment]
Yes--check my `rect-scan-numframes` branch again. Sorry, I updated this, but then forgot to reply.

**Comment by mgraupe** [comment]
Great. The "useTaskDuration" is stored.

On the other hand, I get the following error after a run in the task
manager. Something to do with the restoreState call in the Imaging
analsysisModule:

2016.04.25 11:11:58 Unexpected error:
TypeError: 'bool' object has no attribute '**getitem**'
  File "acq4\modules\TaskRunner\analysisModules\Imaging\Imaging.py", line
100, in newFrame
    self.update()  # updates image
  File "acq4\modules\TaskRunner\analysisModules\Imaging\Imaging.py", line
174, in update
    rs.restoreState(prog['scanInfo'])
  File "acq4\pyqtgraph\parametertree\SystemSolver.py", line 243, in
restoreState
    self.set(name, var[0], var[1])

Any idea?

Thanks,
Michael

On Mon, Apr 25, 2016 at 9:54 AM, Luke Campagnola notifications@github.com
wrote:

> Yes--check my rect-scan-numframes branch again. Sorry, I updated this,
> but then forgot to reply.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/campagnola/acq4/pull/1#issuecomment-214193105

## 

Michael Graupner (PhD)
Brain Physiology Lab, Université Paris Descartes
http://www.biomedicale.parisdescartes.fr/~mgraupe/
michael.graupner@parisdescartes.fr

**Comment by mgraupe** [comment]
I get the following error after a run in the task manager. Something to do with the restoreState call in the Imaging analsysisModule:

2016.04.25 11:11:58 Unexpected error: 
TypeError: 'bool' object has no attribute '**getitem**'
  File "acq4\modules\TaskRunner\analysisModules\Imaging\Imaging.py", line 100, in newFrame
    self.update()  # updates image
  File "acq4\modules\TaskRunner\analysisModules\Imaging\Imaging.py", line 174, in update
    rs.restoreState(prog['scanInfo'])
  File "acq4\pyqtgraph\parametertree\SystemSolver.py", line 243, in restoreState
    self.set(name, var[0], var[1])

Any idea how to fix this? 

Thanks,
Michael

**Comment by campagnola** [comment]
Should be fixed now. Sorry for all the bugs; I'm still testing without real hardware.

**Comment by mgraupe** [comment]
Great. Seems to work without a hitch after a first test. 

Thanks.

**Pull request merged**
